runtime: nodejs18

env_variables:
  MODE: ${{ secrets.MODE }}
  PORT: ${{ secrets.PORT }}
  MONGO_URI: ${{ secrets.MONGO_URI }}

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  min_instances: 1
  max_instances: 10