version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - MODE=${MODE}
      - AUTH0_CLIENTID=${AUTH0_CLIENTID}
      - AUTH0_SECRET=${AUTH0_SECRET}
      - BASE_URL=${BASE_URL}

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
